import React,{useState}from"react";import{createRoot}from"react-dom/client";import{BrowserProvider,Contract,formatUnits}from"ethers";import"./styles.css";
const GBK="0xdA0638EA374c4c5bF2914E6F4D5B2335dEb8D80D";const abi=["function balanceOf(address) view returns (uint256)"];
const short=a=>a?a.slice(0,6)+"…"+a.slice(-4):"";
function App(){const[account,setAccount]=useState("");const[balance,setBalance]=useState("0");const[tab,setTab]=useState("home");const[msg,setMsg]=useState("");
async function connect(){if(!window.ethereum){setMsg("Open GBKAI Pay in a compatible Web3 wallet.");return}try{setMsg("Connecting…");const p=new BrowserProvider(window.ethereum);await p.send("eth_requestAccounts",[]);const n=await p.getNetwork();if(n.chainId!==56n){await window.ethereum.request({method:"wallet_switchEthereumChain",params:[{chainId:"0x38"}]})}const s=await p.getSigner(),a=await s.getAddress();setAccount(a);const t=new Contract(GBK,abi,p);setBalance(Number(formatUnits(await t.balanceOf(a),8)).toLocaleString(undefined,{maximumFractionDigits:4}));setMsg("Connected to BNB Smart Chain.");}catch(e){setMsg(e?.shortMessage||e?.message||"Connection failed.")}}
return <div className="app"><header><a className="brand" href="#" onClick={()=>setTab("home")}><b>GB</b><span><strong>GBKAI <i>Pay</i></strong><small>Global blockchain payments</small></span></a><nav>{["home","pay","receive","activity"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav><button className="connect" onClick={connect}>{account?short(account):"Connect Wallet"}</button></header>
<main><section className="hero"><div><label>GBANK APY • GBK • BNB SMART CHAIN</label><h1>Pay globally.<br/><em>Powered by GBKAI.</em></h1><p>A simple payment layer for GBank APY (GBK), stablecoins, merchants and AI-powered services.</p><div className="actions"><button className="primary" onClick={connect}>Connect & Pay</button><button className="secondary" onClick={()=>setTab("receive")}>Receive Payment</button></div>{msg&&<div className="msg">{msg}</div>}</div><div className="wallet"><div className="top">GBK WALLET <span>● Live</span></div><small>Available GBK</small><strong>{balance}</strong><code>{account||"Connect wallet to view balance"}</code><div className="walletBtns"><button onClick={()=>setTab("pay")}>↗ Pay</button><button onClick={()=>setTab("receive")}>↙ Receive</button></div></div></section>
<section className="cards">{[["01","GBK Payments","Use GBank APY (GBK) for supported ecosystem payments."],["02","Stablecoins","Ready for stablecoin payment rails and merchant settlement."],["03","Merchant Tools","QR, payment links, invoices and transaction history."],["04","ZK Ready","Future privacy-preserving verification for selected flows."]].map(x=><article><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section>
<section className="panel">{tab==="home"?<><label>HOW IT WORKS</label><h2>Ask • Connect • Pay • Grow</h2><div className="steps">{[["01","Choose","Select a service or merchant."],["02","Connect","Connect a BNB Smart Chain wallet."],["03","Pay","Use GBK or a supported method."],["04","Verify","Future ZK infrastructure can verify selected conditions."],["05","Settle","Merchant settlement follows."]].map(x=><div><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></>:tab==="pay"?<div className="empty"><h2>Pay with GBK</h2><p>Core checkout is ready for the next smart-contract integration.</p><button className="primary" onClick={connect}>Connect Wallet</button></div>:tab==="receive"?<div className="empty"><h2>Receive GBK</h2><p>Your connected wallet can be used as the receiving address.</p><code>{account||"Connect wallet first"}</code></div>:<div className="empty"><h2>Transaction Activity</h2><p>BNB Chain indexing will be connected in the next integration stage.</p></div>}</section></main><footer>GBKAI Pay · GBank APY (GBK) · BNB Smart Chain · AI + ZK Ready</footer></div>}
createRoot(document.getElementById("root")).render(<App/>);